---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.19.8
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
      - ./.weaviate_data:/var/lib/weaviate
    environment:
      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
      QUERY_DEFAULTS_LIMIT: 25
      DISK_USE_READONLY_PERCENTAGE: 98
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'
      ENABLE_MODULES: 'multi2vec-clip'
      CLUSTER_HOSTNAME: 'node1'
  multi2vec-clip:
    ports:
      - 9090:8080
    image: semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32
    # command: uvicorn app:app --host 0.0.0.0 --port 8080 --workers 4

    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  # qna-transformers:
  #   image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
  #   environment:
  #     ENABLE_CUDA: '1'
  #     NVIDIA_VISIBLE_DEVICES: 'all'
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - capabilities: 
  #           - 'gpu'
...
